apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-dev-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
      - name: frontend
        image: gcr.io/jenkins-test-214312/frontend:v1
        ports:
        - name: frontend-port
          containerPort: 8100
        env:
        - name: BACKEND_URL
          value: "http://backend:8200"