apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
        env: production
    spec:
      containers:
      - name: sample
        image: gcr.io/jenkins-test-214312/sample:v1
        ports:
        - name: sample-port
          containerPort: 3000
      imagePullSecrets:
      - name: registrykey